# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-27 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('pub', models.CharField(max_length=50, null=True, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default='9999', max_digits=7, null=True, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, default='9999', max_digits=7, verbose_name='零售价')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年龄')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='书名')),
                ('pub', models.CharField(max_length=50, null=True, verbose_name='出版社')),
                ('price', models.DecimalField(decimal_places=2, default='9999', max_digits=7, null=True, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, default='9999', max_digits=7, verbose_name='零售价')),
            ],
        ),
    ]
