# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-09-10 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='This is a good book!', max_length=200),
        ),
    ]
